services:
  opponent-api:
    build:
      context: ./OpponentAPI
    image: othello-opponent-api
    ports:
      - "5000:5000"
    restart: unless-stopped

  game-api:
    build:
      context: ./GameAPI/OthelloGameAPI
    image: othello-game-api
    ports:
      - "8080:8080"
    restart: unless-stopped

  gameplay-spa:
    build:
      context: ./GameplaySPA
    ports:
      - "5173:80"
    restart: unless-stopped